---
microservice_name: eureka-sidecar
user: vagrant
hostpath_home: "/home/{{ user }}"
hostpath_codebase: "{{ hostpath_home}}/{{ microservice_name }}"

supervisord_home: "/etc/supervisor"

# Packages
required_packages:
 - { "package": "nodejs-dbg", "version": "0.10.25~dfsg2-2ubuntu1" }
 - { "package": "nodejs-dev", "version": "0.10.25~dfsg2-2ubuntu1" }
 - { "package": "npm", "version": "1.3.10~dfsg-1" }
 - { "package": "supervisor", "version": "3.0b2-1" }
 - { "package": "python-pip", "version": "1.5.4-1" }

# Packages
npm_global_packages:
 - { "package": "instanbul", "version": "~0.3.11" }
